### ISSUE TITLE
Missing caverealms:obsidian_*

### ISSUE THREAD

**Issue by VanessaE** [Zeno-/caverealms_lite#22]
I switched from caverealms (not sure if it was @Zeno-'s fork, https://github.com/Zeno-/minetest-caverealms, or @HeroOfTheWinds original), to your caverealms_lite, and am finding there are a number of nodes that are no longer defined.  So far, they're caverealms:obsidian_1 through _4 (not sure how high it goes).

![Screenshot_2019-04-14_03-01-14](https://user-images.githubusercontent.com/1733537/56089489-9966ca80-5e61-11e9-9ce4-51c161df8a47.png)

A user who is familiar with these formations says these unknown nodes used to be just normal, whole obsdian cubes, so maybe some aliases to default:obsidian would fix them?

**Comment by VanessaE** [comment]
I just stuck this at the end of nodes.lua, solved the problem well enough:

```lua
minetest.register_alias("caverealms:obsidian", "default:obsidian")
minetest.register_alias("caverealms:obsidian_1", "default:obsidian")
minetest.register_alias("caverealms:obsidian_2", "default:obsidian")
minetest.register_alias("caverealms:obsidian_3", "default:obsidian")
```

**Comment by Ezhh** [comment]
Sorry for the slow answer - very out of it right now but I'm intending to work on this mod before any of my others once study is out of the way for the year. 

I don't think this obsidian was present in the version I tested with, and don't remember ever seeing it in the original cave realms. A quick test doesn't show me those nodes in either the HeroOfTheWinds version or Zeno's version, so it might be something you've added yourself? The texture in your screenshot looks like one from homedecor, not one in caverealms itself, but I might be mistaken?

I'd rather not add aliases for a customised fork of the original caverealms, whereas if these are in the original (or another commonly used version), they should be added. I'd just need to know which is the case.

**Comment by VanessaE** [comment]
Yes, I think those are embers you see in the screenshot, but Home Decor does not place them.  Probably just optional support in @Zeno-'s fork for Semmett9's fake_fire mod (which can be found in HD).

In any case, I'm only concerned with the unknown nodes surrounding the embers. :wink:  Damned if I can find an original source though, everything keeps pointing back to old forks of Dreambuilder, but I know it was something @Zeno- added in a fork he maintained...

\*searches around\*

Here's something:  https://github.com/beyondlimits/dreambuilder_game/commit/7a378b0a104136ccb40422e594e1288847ea606b

By "MTZ branch", it surely means an unpublished fork of this mod that was used on @Zeno-'s "Onez Minetest Server".  I hosted that for a decent while on daconcepts.com, then it went offline, and now I'm running it again, under my own banner.  Best guess, he probably sent me a ZIP or tarball of the server's files to set it up initially when his own hosting failed him, then had me import caverealms from the server's mods directory to use on my other servers.  I believe it was a performance issue that prompted us to use his fork.

(Incidentally, that's a fork of Dreambuilder from back when I shipped it as a game, and it appears to be unaltered and complete from the first commit up to the point where I turned it into a simple modpack.   Good bit of history there).

**Comment by HeroOfTheWinds** [comment]
It's been a long time, but I do recall making an obsidian-themed biome in the really deep portion of CaveRealms.  You had to dig down past the lava biome layer to get to it, and it was accompanied by a salt biome and a coal dust biome.

Sorry I kinda abandoned the project, college happened and now life in the working world.  Glad to see people still keeping this alive though!

**Comment by deezl** [comment]
The MTZ branch on Zeno-'s page has the obsidian stuff in it. https://github.com/Zeno-/minetest-caverealms/blob/mtz/nodes.lua

**Comment by Ezhh** [comment]
Okay, so the question is how likely is it anyone else will use that version and might then convert to this one? I hate alias clutter, and (I think?) that's the only scenario where adding it would be justified.

@HeroOfTheWinds The original caverealms was one of my favourite MT mods of all time. No need of any apologies! And yes, the obsidian biome itself is preserved in this version. We did adjust some of the textures there, but there shouldn't be any unknown node issues when switching between your original and this.

**Comment by VanessaE** [comment]
I imagine a lot of people would, for the sake of performance.  I did on 6 of my worlds :)

**Comment by Zeno-** [comment]
Sorry, I',ve been MIA. I just checked the TODO list I'd created before handing this repo over, and this issue is on it. At the time it was low-priority but since the fix is easy, why not just implement it?

**Comment by Zeno-** [comment]
Yes, the obsidian stuff was specifically only ever used (as far as I knew until now anyway lol) on MTZ, which is why I never made a PR to @HeroOfTheWinds and why it was low on my TODO list.

**Comment by Ezhh** [comment]
Okay, if someone makes a PR I'm fine with merging. (Or @Zeno- should still have access to do it as well.)
