### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by daytonnvpaul** [Zeno-/caverealms_lite#23]
I had a player ask if it was possible to add a sapling like grow routine to the glow crystals, as in other plants.

**Comment by Ezhh** [comment]
Sorry for the slow answer:

Is it possible? Probably. But I doubt there is an efficient way to do it, and caverealms_lite was aimed at being efficient and not too intensive to run, so I'd rather not add something like this. I also don't consider the crystals to be plants, so it wouldn't fit in.
